- name: My First Playbook
  hosts: all
  remote_user: ec2-user
  vars_prompt:
    - name: trello_api_token
      prompt: "Enter your Trello API token:"
      private: yes
    - name: trello_api_key
      prompt: "Enter your Trello API key:"
      private: yes
  tasks: 
    - name: Install Git and Python
      ansible.builtin.yum:
        name: 
          - git
          - python3
        state: present
      become: yes
    - name: Install Poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
        creates: poetry.txt
    - name: Create directory for the To-Do App
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0755"
      become: yes
    - name: Get the latest version of your code with Git
      ansible.builtin.git:
        repo: "https://github.com/11braemm/DevOps-Course-Starter"
        dest: "/opt/todoapp"
        version: "main"
        force: "yes"
    - name: Install project dependencies using Poetry
      ansible.builtin.command: "/home/ec2-user/.local/bin/poetry install"
      args:
        chdir: "/opt/todoapp"
    - name: Create .env file
      ansible.builtin.template:
        src: ".env.j2"
        dest: "/opt/todoapp/.env"
    - name: Copy todoapp.service to managed node
      ansible.builtin.copy:
        src: "todoapp.service"
        dest: "/etc/systemd/system/todoapp.service"
      become: yes
    - name: Start todoapp service
      ansible.builtin.systemd:
        name: todoapp
        state: restarted
        daemon_reload: yes
      become: yes