name: Continuous Integration
on:
  push:
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test

  deploy:
    name: Push to Docker Hub and trigger App Service to deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/module-9-set-up-deployment-pipeline' }}
    steps:
    - uses: actions/checkout@v4
    - run: echo hello deploy

